### ISSUE TITLE
Kitsune relicensing

### ISSUE THREAD

**Issue by aumetra** [SlimeyIceCream/Mc-modpack#1]
I tried contacting you over a few channels but didn't manage unfortunately, so I'm just trying here. Sorry if it isn't the best spot.  
Would you mind taking a look here and, if it all seems fine to you, accepting the relicensing terms?

https://github.com/kitsune-soc/kitsune/pull/479

**Comment by SlimeyIceCream** [comment]
😭 sorry

**Comment by aumetra** [comment]
Don't worry about it, all good! Sorry if what I wrote sounded a bit harsh, I'm not the best at these things..

(There's also private stuff that has been draining me a bit lately, so that's that)
